FROM maven:3.3-jdk-8 AS builder
COPY ./grpc-java /grpc-java
WORKDIR /grpc-java/examples
RUN ./gradlew installDist -PskipAndroid=true -PskipCodegen=true


FROM openjdk:8-jre-alpine
COPY --from=builder /grpc-java/examples/build/install/examples /grpc-java/examples/build/install/examples
WORKDIR /grpc-java/examples
ENTRYPOINT [ "./build/install/examples/bin/hello-world-server" ]